---
title: "p8105_hw6_wc2788"
author: "Wen Cheng"
date: "11/29/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
```

## Problem 1

```{r}
#load and clean data
birthweight <- read_csv("birthweight.csv") %>%
  janitor::clean_names() %>%
#convert numeric to factor
  mutate(babysex = factor(babysex,
                          levels = c(1, 2),
                          labels = c("male", "female")),
         frace = factor(frace, 
                        levels = c(1, 2, 3, 4, 8, 9), 
                        labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
         malform = factor(malform, 
                          levels = c(0, 1),
                          labels = c("absent", "present")),
         mrace = factor(mrace, 
                        levels = c(1, 2, 3, 4, 8), 
                        labels = c("White", "Black", "Asian", "Puerto Rican", "Other")))

 #check for missing data
sum(is.na(birthweight))
```
There are `nrow(birthweight)` observations and `ncol(birthweight)` variables in this dataset, and no missing value.

```{r}
#propose a regression model
fit = lm(bwt ~ babysex + blength + delwt + fincome + frace + mrace + wtgain, data = birthweight) 
summary(fit)
```

```{r}
birthweight %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()
```






